<?php
/**
 * Feature Bingo cards - Projects (3.2.0). See includes/feature_bingo.php for the format.
 *
 * Projects needs no switching on, so these cards light as the module is used:
 * a first project, a plan split into phases, work filed under it, and the
 * project joined to the records it touches.
 */

return [
    [
        'id'       => 'projects.first',
        'module'   => 'projects',
        'tier'     => 'recommended',
        'category' => 'organisation',
        'title'    => 'Run a project',
        'what'     => 'A project gathers the tasks behind a bigger piece of work - an office move, a laptop refresh, a migration - with a goal, dates and a project manager.',
        'why'      => 'The portfolio shows every project\'s progress and health at a glance, worked out from its tasks rather than from somebody\'s update.',
        'done'     => 'At least one project exists.',
        'link'     => 'projects/',
        'check'    => ['rows', 'projects'],
    ],
    [
        'id'       => 'projects.plan',
        'module'   => 'projects',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'A plan in phases',
        'what'     => 'A project split into phases, stages or sprints, each with its own tasks and dates. Run it Simple, Staged (PRINCE2-style) or Agile, and change your mind later.',
        'why'      => 'Everyone can see which part of the work is happening now, and the ring shows how far along each phase is.',
        'done'     => 'At least one project has a phase, stage or sprint with a task in it.',
        'link'     => 'projects/',
        'check'    => ['sql', 'SELECT COUNT(*) FROM tasks t JOIN project_stages s ON s.id = t.project_stage_id'],
    ],
    [
        'id'       => 'projects.raci',
        'module'   => 'projects',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Who does what (RACI)',
        'what'     => 'A project\'s People tab gives each person a role, its Scope tab lists the deliverables, and the RACI matrix says who is Responsible, Accountable, Consulted and Informed for each.',
        'why'      => 'Nobody has to ask who owns a deliverable or who should have been told - and every row has exactly one person accountable.',
        'done'     => 'At least one RACI letter has been set on a project.',
        'link'     => 'projects/',
        'check'    => ['rows', 'project_raci'],
    ],
    [
        'id'       => 'projects.moscow',
        'module'   => 'projects',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Scope prioritised Must, Should, Could, Won\'t',
        'what'     => 'Deliverables and requirements on a MoSCoW board you drag between, each with a status and a done-when.',
        'why'      => 'When time runs short, everyone already agrees what can give - the Won\'t column is a decision, not an argument.',
        'done'     => 'At least one deliverable on a project has a MoSCoW priority.',
        'link'     => 'projects/',
        'check'    => ['rows', 'project_items', 'moscow IS NOT NULL'],
    ],
    [
        'id'       => 'projects.raid',
        'module'   => 'projects',
        'tier'     => 'recommended',
        'category' => 'governance',
        'title'    => 'A RAID log with a risk heat map',
        'what'     => 'Risks, assumptions, issues and decisions on a project\'s RAID tab, each risk scored probability times impact on a five-by-five heat map.',
        'why'      => 'What could go wrong is written down with an owner and a plan, instead of living in somebody\'s head until it happens.',
        'done'     => 'At least one risk has been logged on a project.',
        'link'     => 'projects/',
        'check'    => ['rows', 'project_raid', "type = 'risk'"],
    ],
    [
        'id'       => 'projects.gates',
        'module'   => 'projects',
        'tier'     => 'extra',
        'category' => 'governance',
        'title'    => 'Stage gates and tolerances',
        'what'     => 'A staged project\'s Gates tab: a business case, a go or stop decision at the end of every stage, and tolerances that raise an exception when the project drifts too far.',
        'why'      => 'The project manages by exception - the board only steps in when a tolerance is breached, and every gate decision is on record.',
        'done'     => 'At least one stage gate decision has been recorded.',
        'link'     => 'projects/',
        'check'    => ['rows', 'project_stages', 'gate_decision IS NOT NULL'],
    ],
    [
        'id'       => 'projects.asset_targets',
        'module'   => 'projects',
        'tier'     => 'extra',
        'category' => 'insight',
        'title'    => 'Project progress counted from Assets',
        'what'     => 'An asset target on a project\'s Overview counts assets that meet a rule - "Latitude 5430s retired", "Windows 11 everywhere" - with a line of its progress and the list still to do.',
        'why'      => 'A refresh or rollout reports its real progress from the estate itself, and falls behind on the health ring the moment it slips.',
        'done'     => 'At least one project has an asset target.',
        'link'     => 'projects/',
        'check'    => ['rows', 'project_asset_targets'],
    ],
    [
        'id'       => 'projects.connections',
        'module'   => 'projects',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Projects joined to everything else',
        'what'     => 'A project\'s Connections tab links it to the equipment, changes, tickets, contracts, configuration items and knowledge articles it touches.',
        'why'      => 'The changes a project raises, the tickets it causes and the kit it works on sit on one page instead of being hunted for across modules.',
        'done'     => 'At least one project is linked to another record.',
        'link'     => 'projects/',
        'check'    => ['any', [
            ['rows', 'project_assets'], ['rows', 'project_changes'], ['rows', 'project_tickets'],
            ['rows', 'project_contracts'], ['rows', 'project_cmdb_objects'], ['rows', 'project_knowledge_articles'],
        ]],
    ],
    [
        'id'       => 'projects.templates',
        'module'   => 'projects',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Projects started from a template',
        'what'     => 'A new project picks a template - an office move, a laptop refresh, or one saved from your own best project - and arrives with its stages, tasks, scope and risks already planned.',
        'why'      => 'The second office move starts where the first one finished, instead of from a blank page and somebody\'s memory.',
        'done'     => 'At least one project has been started from a template, or a project has been saved as one.',
        'link'     => 'projects/',
        'check'    => ['any', [
            ['rows', 'project_audit', "field_name = 'template_used'"], ['rows', 'project_templates'],
        ]],
    ],
    [
        'id'       => 'projects.calendar',
        'module'   => 'projects',
        'tier'     => 'extra',
        'category' => 'insight',
        'title'    => 'Project dates on the Calendar',
        'what'     => 'Every live project puts its target end date, each open stage its end date and each milestone its date on the shared Calendar in a Projects category, and keeps them there as the plan changes.',
        'why'      => 'The deadline a project is working to sits where the rest of the team already plans their week, instead of only on a page someone has to open.',
        'done'     => 'At least one project date is on the Calendar.',
        'link'     => 'projects/settings/',
        'check'    => ['rows', 'calendar_events', "source IN ('project_end', 'project_stage', 'project_milestone')"],
    ],
    [
        'id'       => 'projects.workflows',
        'module'   => 'projects',
        'tier'     => 'extra',
        'category' => 'automation',
        'title'    => 'A workflow that acts on a project',
        'what'     => 'A workflow triggered by a project - its health changing, a tolerance breached, a stage closing or ending soon - that posts to Teams or Slack, raises a ticket or sends an email.',
        'why'      => 'The people who need to know a project has gone red hear it where they already are, without anybody remembering to tell them.',
        'done'     => 'An active workflow is triggered by a project event.',
        'link'     => 'workflow/',
        'check'    => ['rows', 'workflows', "trigger_event LIKE 'project.%' AND is_active = 1"],
    ],
    [
        'id'       => 'projects.report_pack',
        'module'   => 'projects',
        'tier'     => 'extra',
        'category' => 'insight',
        'title'    => 'Projects in a report pack',
        'what'     => 'A Report Pack with a Projects block - the summary, health, status, milestones or top risks - so the monthly board pack covers the projects without anybody copying figures out.',
        'why'      => 'The board sees which projects are on track, which milestones were met and what could still go wrong, in the same pack as the service figures.',
        'done'     => 'At least one report pack has a Projects block.',
        'link'     => 'reporting/packs/',
        'check'    => ['rows', 'report_packs', "design LIKE '%\"handler\":\"projects.%'"],
    ],
    [
        'id'       => 'projects.announce',
        'module'   => 'projects',
        'tier'     => 'extra',
        'category' => 'communication',
        'title'    => 'Disruption announced from a project',
        'what'     => 'A project announces the disruption it will cause - "Move day: phones down Saturday" - as planned maintenance on Service Status, straight from its Connections tab.',
        'why'      => 'People hear about the outage before it happens, in the place they already look, and it starts and ends on the services by itself.',
        'done'     => 'At least one project has announced disruption on Service Status.',
        'link'     => 'projects/',
        'check'    => ['rows', 'status_planned', 'project_id IS NOT NULL'],
    ],
    [
        'id'       => 'projects.budget',
        'module'   => 'projects',
        'tier'     => 'extra',
        'category' => 'insight',
        'title'    => 'A project budget, planned against actual',
        'what'     => 'Budget lines with planned and actual amounts, contracts and cost centres, and the time logged on the project\'s tasks - priced at your hourly rates if you want.',
        'why'      => 'You see a project going over budget while there is still time to act, not in the post-project review.',
        'done'     => 'At least one project has a budget line.',
        'link'     => 'projects/',
        'check'    => ['rows', 'project_budget_lines'],
    ],
    [
        'id'       => 'projects.ai_reports',
        'module'   => 'projects',
        'tier'     => 'extra',
        'category' => 'insight',
        'title'    => 'An AI project manager',
        'what'     => 'A briefing on what needs attention this week, and highlight, exception and checkpoint reports drafted by the AI from the project itself - for the project manager to check and approve.',
        'why'      => 'The weekly report takes minutes instead of an afternoon, and nothing reaches the board until a person has approved it.',
        'done'     => 'At least one project report has been approved.',
        'link'     => 'projects/',
        'check'    => ['rows', 'project_reports', "status = 'approved'"],
    ],
    [
        'id'       => 'projects.milestones',
        'module'   => 'projects',
        'tier'     => 'recommended',
        'category' => 'insight',
        'title'    => 'Milestones on the Timeline',
        'what'     => 'The dates a project promises - move day, go-live, sign-off - as diamonds on the project\'s Timeline, a Gantt chart of its stages and tasks you can drag to reschedule.',
        'why'      => 'A milestone that slips turns the project amber and tells its manager, so a missed date is news the day it happens, not at the next meeting.',
        'done'     => 'At least one project has a milestone.',
        'link'     => 'projects/',
        'check'    => ['rows', 'project_milestones'],
    ],
    [
        'id'       => 'projects.decision_log',
        'module'   => 'projects',
        'tier'     => 'extra',
        'category' => 'governance',
        'title'    => 'A decision log',
        'what'     => 'Decisions on a project\'s RAID tab recorded when they are made - who decided, when and why - with the follow-up actions that came out of them as tasks.',
        'why'      => 'Six months on, nobody has to remember why the cheaper supplier was chosen: it is written down, with who agreed it and what was done about it.',
        'done'     => 'At least one decision has been recorded with who made it.',
        'link'     => 'projects/',
        'check'    => ['rows', 'project_raid', "type = 'decision' AND decided_by IS NOT NULL"],
    ],
    [
        'id'       => 'projects.capacity',
        'module'   => 'projects',
        'tier'     => 'extra',
        'category' => 'insight',
        'title'    => 'Who has room? (Capacity)',
        'what'     => 'Estimates on project tasks, and the Capacity page: each person\'s load in the weeks ahead - the project work they have left plus their service-desk shifts - against the hours they work.',
        'why'      => 'You see that the engineer on the move is also on the desk three days next week before the move slips, not after.',
        'done'     => 'At least one project task has an estimate.',
        'link'     => 'projects/capacity.php',
        'check'    => ['rows', 'tasks', 'project_id IS NOT NULL AND estimate_hours IS NOT NULL'],
    ],
    [
        'id'       => 'projects.change_control',
        'module'   => 'projects',
        'tier'     => 'extra',
        'category' => 'governance',
        'title'    => 'Change control with baselines',
        'what'     => 'A baseline of each project\'s agreed plan - dates, budget, work and Must scope - with how far it has drifted since, and change requests approved or rejected before the plan moves.',
        'why'      => 'When the board asks why go-live slipped three weeks and the budget grew by a fifth, the answer is on one tab: who asked, why, and who agreed.',
        'done'     => 'At least one change request has been decided.',
        'link'     => 'projects/',
        'check'    => ['rows', 'project_change_requests', "status IN ('approved', 'rejected')"],
    ],
];
