<?php
/** Feature Bingo cards - Service Status: services, incidents and their updates, statuses, impact levels, uptime, and service status on the portal. See includes/feature_bingo.php for the format. */
return [
    [
        'id'       => 'service-status.services',
        'module'   => 'service-status',
        'tier'     => 'recommended',
        'category' => 'customer',
        'title'    => 'Your service catalogue',
        'what'     => 'The IT services your users depend on - Email, VPN, the ERP system - each shown as a card on the status dashboard and in the self-service portal.',
        'why'      => 'Every outage you record, and every uptime figure, hangs off a service. Without the list there is nothing for the status page to show.',
        'done'     => 'At least one service exists that was not created by the demo data importer.',
        'link'     => 'service-status/settings/',
        'check'    => ['rows', 'status_services', 'is_demo = 0'],
    ],
    [
        'id'       => 'service-status.service_descriptions',
        'module'   => 'service-status',
        'tier'     => 'extra',
        'category' => 'customer',
        'title'    => 'Describe each service',
        'what'     => 'A short description on each service explaining what it is, shown beneath its name on the dashboard.',
        'why'      => 'Users do not always know that "Exchange" is their email or that "Citrix" is how they reach the finance system. A line of explanation saves a ticket asking.',
        'done'     => 'At least one real (non-demo) service has a description.',
        'link'     => 'service-status/settings/',
        'check'    => ['rows', 'status_services', "description IS NOT NULL AND description <> '' AND is_demo = 0"],
    ],
    [
        'id'       => 'service-status.first_incident',
        'module'   => 'service-status',
        'tier'     => 'recommended',
        'category' => 'communication',
        'title'    => 'Record a service incident',
        'what'     => 'An incident with a title, a status and the affected services, each at an impact level such as Degraded or Major Outage. The service cards change colour the moment it is saved.',
        'why'      => 'Posting an outage as soon as you know about it answers the question fifty people were about to ring the desk with, and starts the history your uptime figures are built from.',
        'done'     => 'At least one real (non-demo) incident has an affected service linked to it.',
        'link'     => 'service-status/',
        'check'    => ['rows', 'status_incident_services', 'is_demo = 0'],
    ],
    [
        'id'       => 'service-status.external_updates',
        'module'   => 'service-status',
        'tier'     => 'extra',
        'category' => 'customer',
        'title'    => 'External incident updates',
        'what'     => 'Each comment on an incident is either an internal note for your team or an external update written for end users. Internal is the default every time.',
        'why'      => 'Keeping the two apart means you can write freely about what you have ruled out while still giving users a plain-English update they can be shown.',
        'done'     => 'At least one incident update has been marked as external.',
        'link'     => 'service-status/',
        'check'    => ['rows', 'status_incident_updates', 'is_internal = 0'],
    ],
    [
        'id'       => 'service-status.portal_incidents',
        'module'   => 'service-status',
        'tier'     => 'recommended',
        'category' => 'customer',
        'title'    => 'Incidents on the portal',
        'what'     => 'Shows end users the incidents behind an outage, and the updates marked external, in the self-service portal - only what is happening now, recent ones as well, or the full history.',
        'why'      => 'A status page people can check themselves is the cheapest way to cut calls during an outage, and a resolved entry is the reassurance someone affected an hour ago is looking for.',
        'done'     => 'Incidents and their external updates are switched on for the portal (off by default).',
        'link'     => 'system/status-portal/',
        'check'    => ['setting', 'service_status_portal_updates', 'eq', '1'],
    ],
    [
        'id'       => 'service-status.uptime_window',
        'module'   => 'service-status',
        'tier'     => 'extra',
        'category' => 'insight',
        'title'    => 'Uptime reporting period',
        'what'     => 'The default period - 7, 30, 90 or 365 days - that each service\'s history strip and uptime percentage cover before anyone picks another.',
        'why'      => 'The figure people quote is whichever one they see first. Choosing the period that matches your service reviews means the dashboard and the monthly report agree.',
        'done'     => 'The uptime reporting period has been saved under Settings -> Uptime.',
        'link'     => 'service-status/settings/',
        'check'    => ['setting', 'status_uptime_window_days', 'nonempty'],
    ],
    [
        'id'       => 'service-status.uptime_portal',
        'module'   => 'service-status',
        'tier'     => 'extra',
        'category' => 'customer',
        'title'    => 'Uptime in the portal',
        'what'     => 'Shows each service\'s uptime percentage to customers in the self-service portal, not just its current status.',
        'why'      => 'A published availability figure is a strong statement of confidence in your service - and a commitment, so it is off until you choose it.',
        'done'     => 'Uptime is switched on for the portal (off by default).',
        'link'     => 'service-status/settings/',
        'check'    => ['setting', 'status_uptime_show_portal', 'eq', '1'],
    ],
    [
        'id'       => 'service-status.downtime_rules',
        'module'   => 'service-status',
        'tier'     => 'extra',
        'category' => 'insight',
        'title'    => 'What counts as downtime',
        'what'     => 'Each impact level decides whether time spent at it counts against uptime. By default Major Outage, Partial Outage and Degraded count; Maintenance, Operational and No Disruption do not.',
        'why'      => 'If your agreements treat degraded service as available, or planned maintenance as downtime, the uptime figures should say the same as the contract.',
        'done'     => 'A shipped impact level\'s downtime setting has been changed from its default, or a new level has been added.',
        'link'     => 'service-status/settings/',
        'check'    => ['any', [
            ['rows', 'service_impact_levels', "name IN ('Major Outage','Partial Outage','Degraded') AND counts_as_downtime = 0"],
            ['rows', 'service_impact_levels', "name IN ('Maintenance','Operational','No Disruption') AND counts_as_downtime = 1"],
            ['rows', 'service_impact_levels', "name NOT IN ('Major Outage','Partial Outage','Degraded','Maintenance','Operational','No Disruption') AND display_order <> 999"],
        ]],
    ],
    [
        'id'       => 'service-status.impact_levels_tailored',
        'module'   => 'service-status',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Impact levels',
        'what'     => 'The levels a service can be at, from Major Outage to No Disruption, each with a colour and a severity order that decides which one a service shows when several incidents touch it.',
        'why'      => 'Using the words your users already know, and ranking them the way you actually treat them, makes the service cards mean the same thing to everyone reading them.',
        'done'     => 'At least one impact level has a name other than the six shipped ones, or one of those has been removed.',
        'link'     => 'service-status/settings/',
        'check'    => ['any', [
            ['rows', 'service_impact_levels', "name NOT IN ('Major Outage','Partial Outage','Degraded','Maintenance','Operational','No Disruption') AND display_order <> 999"],
            ['sql', 'SELECT COUNT(*) < 6 FROM service_impact_levels'],
        ]],
    ],
    [
        'id'       => 'service-status.incident_statuses_tailored',
        'module'   => 'service-status',
        'tier'     => 'extra',
        'category' => 'communication',
        'title'    => 'Incident statuses',
        'what'     => 'The stages an incident goes through - Investigating, Identified, Monitoring, 3rd Party, Resolved - and which of them mean the incident is over.',
        'why'      => 'These words are what users read on the status page. If your team says "Fix deployed" rather than "Monitoring", the page should too.',
        'done'     => 'At least one incident status has a name other than the five shipped ones, or one of those has been removed.',
        'link'     => 'service-status/settings/',
        'check'    => ['any', [
            ['rows', 'service_incident_statuses', "name NOT IN ('Investigating','Identified','Monitoring','3rd Party','Resolved') AND display_order <> 999"],
            ['sql', 'SELECT COUNT(*) < 5 FROM service_incident_statuses'],
        ]],
    ],
    [
        'id'       => 'service-status.planned',
        'module'   => 'service-status',
        'tier'     => 'extra',
        'category' => 'communication',
        'title'    => 'Planned maintenance announced in advance',
        'what'     => 'Planned maintenance shows as upcoming on the board and the portal, becomes an incident at its start and resolves at its end - by itself.',
        'why'      => 'Nobody is surprised by planned work, the services are not shown down days early, and maintenance never counts against uptime.',
        'done'     => 'At least one piece of maintenance has been planned.',
        'link'     => 'service-status/',
        'check'    => ['rows', 'status_planned'],
    ],
];