<?php
/**
 * Feature Bingo cards - System: REST API, webhooks, calendar sync, AI (central),
 * integrations (issue trackers, Slack; Tika is in system-core.php). See includes/feature_bingo.php for the format.
 */

// Every AI feature namespace from aiSettingsRegistry() (includes/ai_settings.php).
// Each stores <ns>_provider / <ns>_model / <ns>_api_key / <ns>_reasoning in system_settings.
$aiNs = ['knowledge_ai', 'cmdb_ai', 'workflow_ai', 'forms_ai', 'tickets_reply_cleanup',
         'problem_ai', 'lms_ai', 'knowledge_writeup', 'warroom_ai'];
$aiKeys = function (string $suffix) use ($aiNs): string {
    return "'" . implode("', '", array_map(fn($n) => $n . '_' . $suffix, $aiNs)) . "'";
};

return [
    // ── REST API ────────────────────────────────────────────────────────────
    [
        'id'       => 'system.rest_api_key',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'integrations',
        'title'    => 'REST API key',
        'what'     => 'A key for the REST API (v1), which lets another system read and write FreeITSM records - tickets, assets, users and more - acting as a named analyst.',
        'why'      => 'Your HR system, monitoring tool or a script can raise tickets and keep records in step on its own, instead of someone copying things across by hand.',
        'done'     => 'At least one active REST API key exists.',
        'link'     => 'system/api/',
        'check'    => ['rows', 'api_keys', 'active = 1'],
    ],
    [
        'id'       => 'system.mcp_server',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'ai',
        'title'    => 'An AI assistant connected through MCP',
        'what'     => 'An API key with the MCP server permission, so an assistant such as Claude Code can read FreeITSM - projects, incidents, service status, changes - read-only and as one analyst.',
        'why'      => 'Ask "which projects are off track and why" or "what changed this morning" in plain words, and get the answer from your own data.',
        'done'     => 'An active API key has the MCP server permission.',
        'link'     => 'system/api/',
        'check'    => ['rows', 'api_keys', "active = 1 AND permissions LIKE '%\"mcp\"%'"],
    ],
    [
        'id'       => 'system.api_key_expiry',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'security',
        'title'    => 'API keys that expire',
        'what'     => 'An expiry date on a REST API key, after which the key stops working without anyone having to remember to revoke it.',
        'why'      => 'A key made for a one-off migration or a contractor is the kind that gets forgotten and keeps working for years. An expiry date closes it for you.',
        'done'     => 'At least one REST API key has an expiry date.',
        'link'     => 'system/api/',
        'check'    => ['rows', 'api_keys', 'expires_at IS NOT NULL'],
    ],
    [
        'id'       => 'system.api_key_rate_limit',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'security',
        'title'    => 'API rate limits',
        'what'     => 'A cap on how many requests per minute one REST API key may make.',
        'why'      => 'A runaway script or a leaked key cannot hammer the server and slow FreeITSM down for your analysts.',
        'done'     => 'At least one REST API key has a rate limit set.',
        'link'     => 'system/api/',
        'check'    => ['rows', 'api_keys', 'rate_limit_per_minute IS NOT NULL AND rate_limit_per_minute > 0'],
    ],
    [
        'id'       => 'system.api_key_company_scope',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'security',
        'title'    => 'API keys limited to companies',
        'what'     => 'A REST API key that can only see and change the records of the companies you choose, rather than all of them.',
        'why'      => 'When you run the desk for several companies, a key handed to one client or one of their systems cannot reach another client\'s data.',
        'done'     => 'At least one REST API key is limited to specific companies.',
        'link'     => 'system/api/',
        'check'    => ['rows', 'api_keys', "company_ids IS NOT NULL AND company_ids <> '' AND company_ids <> '[]'"],
    ],

    // ── Webhooks ────────────────────────────────────────────────────────────
    [
        'id'       => 'system.webhook_worker',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'automation',
        'title'    => 'Webhook delivery worker',
        'what'     => 'The scheduled job (cron/webhook_deliveries.php) that sends queued webhooks, retrying ones that fail with a back-off.',
        'why'      => 'Workflow webhooks to Slack, Teams or anything else are only queued until this runs. Without it they sit in the queue and never leave the building.',
        'done'     => 'The webhook delivery worker has run in the last 7 days.',
        'link'     => 'system/webhooks/',
        'check'    => ['sql', "SELECT COUNT(*) FROM system_settings WHERE setting_key = 'webhook_cron_last_run' AND setting_value >= UTC_TIMESTAMP() - INTERVAL 7 DAY"],
    ],
    [
        'id'       => 'system.webhook_payload_retention',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'security',
        'title'    => 'Webhook payload retention',
        'what'     => 'How long the full body of each sent webhook is kept for replay before it is blanked - from not at all to forever. The delivery record itself stays.',
        'why'      => 'A "full record" webhook is a whole ticket in plain text. Deciding how long those copies are kept is a data-protection choice worth making on purpose.',
        'done'     => 'An administrator has saved a payload retention period (the 7-day default until then).',
        'link'     => 'system/webhooks/',
        'check'    => ['setting', 'webhook_payload_retention_days', 'nonempty'],
    ],

    // ── Calendar sync ───────────────────────────────────────────────────────
    [
        'id'       => 'system.calendar_sync_microsoft',
        'module'   => 'system',
        'tier'     => 'recommended',
        'category' => 'integrations',
        'title'    => 'Microsoft 365 calendar sync',
        'what'     => 'A connection that writes each analyst\'s scheduled tickets and tasks into their own Outlook calendar, using a Microsoft app registration.',
        'why'      => 'Work booked in FreeITSM shows up where people actually plan their day, so a scheduled visit is not double-booked against a meeting.',
        'done'     => 'At least one active Microsoft 365 calendar connection exists.',
        'link'     => 'system/calendar-sync/',
        'check'    => ['rows', 'calendar_connections', "provider = 'microsoft' AND is_active = 1"],
    ],
    [
        'id'       => 'system.calendar_sync_caldav',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'integrations',
        'title'    => 'CalDAV calendar sync',
        'what'     => 'A connection to a CalDAV server (Nextcloud, Baikal, Radicale, iCloud, Fastmail and others) that writes each analyst\'s scheduled work into their calendar there.',
        'why'      => 'Teams not on Microsoft 365 still get their scheduled tickets in the calendar they use, each analyst signing in as themselves.',
        'done'     => 'At least one active CalDAV calendar connection exists.',
        'link'     => 'system/calendar-sync/',
        'check'    => ['rows', 'calendar_connections', "provider = 'caldav' AND is_active = 1"],
    ],
    [
        'id'       => 'system.calendar_sync_in_use',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Analysts syncing their calendars',
        'what'     => 'Analysts who have switched calendar sync or a subscription link on for themselves under Preferences.',
        'why'      => 'A connection nobody uses does nothing. Once analysts opt in, their scheduled work appears in their calendar without them copying it across.',
        'done'     => 'At least one analyst has calendar sync or a subscription link switched on.',
        'link'     => 'system/calendar-sync/',
        'check'    => ['rows', 'calendar_enrolments', "mode <> 'off'"],
    ],
    [
        'id'       => 'system.calendar_mailbox_override',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'integrations',
        'title'    => 'Calendar mailbox per analyst',
        'what'     => 'The mailbox an analyst\'s work is written to, set by an administrator when it differs from the email address on their FreeITSM account.',
        'why'      => 'A local account or a directory import often carries an address that is not the real mailbox, and sync then writes to a calendar nobody looks at.',
        'done'     => 'At least one analyst has a calendar mailbox address set.',
        'link'     => 'system/calendar-sync/',
        'check'    => ['rows', 'calendar_enrolments', "calendar_address IS NOT NULL AND calendar_address <> ''"],
    ],
    [
        'id'       => 'system.calendar_two_way',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Two-way calendar sync',
        'what'     => 'The scheduled job (cron/calendar_sync_pull.php) that reads changes back from analysts\' calendars, so moving an appointment in Outlook moves the ticket.',
        'why'      => 'Without it the sync is one way: an analyst who drags an appointment to Thursday leaves the ticket still booked for Tuesday.',
        'done'     => 'Changes have been read back from at least one analyst\'s calendar.',
        'link'     => 'system/calendar-sync/',
        'check'    => ['rows', 'calendar_enrolments', "mode <> 'off' AND delta_synced_datetime IS NOT NULL"],
    ],
    [
        'id'       => 'system.calendar_accept_deletes',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Deleting an appointment unschedules',
        'what'     => 'When on, deleting one of these appointments in a calendar takes the schedule off the ticket as well.',
        'why'      => 'Analysts who manage their week from Outlook can cancel a booking in one place, rather than in the calendar and again in FreeITSM.',
        'done'     => 'The switch is on (it is off by default).',
        'link'     => 'system/calendar-sync/',
        'check'    => ['setting', 'tickets_calendar_accept_deletes', 'eq', '1'],
    ],
    [
        'id'       => 'system.calendar_change_notifications',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'integrations',
        'title'    => 'Instant calendar change notifications',
        'what'     => 'A public HTTPS address Microsoft calls the moment an analyst changes one of these appointments, instead of waiting for the next scheduled check.',
        'why'      => 'A rescheduled appointment reaches the ticket in seconds rather than minutes, which matters when a dispatcher is watching the board.',
        'done'     => 'A notification URL has been saved.',
        'link'     => 'system/calendar-sync/',
        'check'    => ['setting', 'tickets_calendar_notify_url', 'nonempty'],
    ],
    [
        'id'       => 'system.calendar_feed_policy',
        'module'   => 'system',
        'tier'     => 'recommended',
        'category' => 'security',
        'title'    => 'Calendar subscription link policy',
        'what'     => 'Whether analysts may publish a subscribe (.ics) link to their schedule, and if so whether it may show ticket subjects or only ticket numbers.',
        'why'      => 'A subscription link is readable by anyone who has it. Deciding what it may reveal keeps ticket subjects from leaking into personal calendars.',
        'done'     => 'An administrator has saved the subscription link policy (it allows full detail until then).',
        'link'     => 'system/calendar-sync/',
        'check'    => ['setting', 'tickets_schedule_feed_mode', 'nonempty'],
    ],

    // ── AI (central) ────────────────────────────────────────────────────────
    [
        'id'       => 'system.ai_connected',
        'module'   => 'system',
        'tier'     => 'recommended',
        'category' => 'ai',
        'title'    => 'An AI provider connected',
        'what'     => 'An API key for Anthropic, OpenAI, OpenRouter or Azure OpenAI on at least one of FreeITSM\'s AI features. Each module keeps its own key so billing and access stay separate.',
        'why'      => 'Nothing AI-powered - drafting articles, summarising incidents, building workflows and forms from a sentence - works until a provider has a key.',
        'done'     => 'At least one AI feature has an API key stored.',
        'link'     => 'system/ai/',
        'check'    => ['sql', "SELECT COUNT(*) FROM system_settings WHERE setting_key IN (" . $aiKeys('api_key') . ") AND setting_value IS NOT NULL AND setting_value <> ''"],
    ],
    [
        'id'       => 'system.ai_extended_thinking',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'ai',
        'title'    => 'AI extended thinking',
        'what'     => 'A per-feature switch on System -> AI that lets a reasoning model think before it answers. It is off by default and only has an effect through OpenRouter.',
        'why'      => 'Most AI jobs here are summarising and drafting, where thinking only adds wait. Switch it on for a feature whose answers turn out to need real deliberation.',
        'done'     => 'Extended thinking is switched on for at least one AI feature.',
        'link'     => 'system/ai/',
        'check'    => ['sql', "SELECT COUNT(*) FROM system_settings WHERE setting_key IN (" . $aiKeys('reasoning') . ") AND setting_value = '1'"],
    ],
    [
        'id'       => 'system.ai_openrouter',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'ai',
        'title'    => 'AI through OpenRouter',
        'what'     => 'At least one AI feature uses OpenRouter, a single account that reaches models from many providers.',
        'why'      => 'You can try a cheaper or faster model for one feature without opening another provider account, and it is the only route where the extended-thinking switch applies.',
        'done'     => 'At least one AI feature is set to the OpenRouter provider.',
        'link'     => 'system/ai/',
        'check'    => ['sql', "SELECT COUNT(*) FROM system_settings WHERE setting_key IN (" . $aiKeys('provider') . ") AND setting_value = 'openrouter'"],
    ],
    [
        'id'       => 'system.ai_azure_openai',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'ai',
        'title'    => 'AI through Azure OpenAI',
        'what'     => 'At least one AI feature uses your own Azure OpenAI deployment, addressed by endpoint, deployment name and API version.',
        'why'      => 'Text sent to the model stays inside your organisation\'s Azure tenant and its data-handling terms, which some compliance teams require.',
        'done'     => 'At least one AI feature is set to the Azure OpenAI provider.',
        'link'     => 'system/ai/',
        'check'    => ['sql', "SELECT COUNT(*) FROM system_settings WHERE setting_key IN (" . $aiKeys('provider') . ") AND setting_value = 'azure'"],
    ],

    // ── Integrations: issue trackers ────────────────────────────────────────
    [
        'id'       => 'system.jira_connection',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'integrations',
        'title'    => 'Jira connection',
        'what'     => 'A connection to a Jira Cloud or Data Center site, so a ticket that turns out to be a bug can be raised as a Jira issue and its status followed from the ticket.',
        'why'      => 'The service desk stops chasing developers by email: the issue is raised in one click and the ticket shows when it moves or is fixed.',
        'done'     => 'At least one active Jira connection exists.',
        'link'     => 'system/integrations/provider.php?provider=jira',
        'check'    => ['rows', 'integration_connections', "provider = 'jira' AND is_active = 1"],
    ],
    [
        'id'       => 'system.azure_devops_connection',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'integrations',
        'title'    => 'Azure DevOps connection',
        'what'     => 'A connection to an Azure DevOps organisation (Services or Server), so tickets can be raised as work items and their state followed from the ticket.',
        'why'      => 'Bugs reach the development backlog with the ticket linked, and the desk sees when the work item is resolved without asking.',
        'done'     => 'At least one active Azure DevOps connection exists.',
        'link'     => 'system/integrations/provider.php?provider=azuredevops',
        'check'    => ['rows', 'integration_connections', "provider = 'azuredevops' AND is_active = 1"],
    ],
    [
        'id'       => 'system.tracker_inbound_comments',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'integrations',
        'title'    => 'Tracker comments into tickets',
        'what'     => '"Accept updates" on a tracker connection: comments written on the linked issue arrive on the ticket as internal notes, never shown to the requester.',
        'why'      => 'When a developer asks a question or says a fix is in, the analyst sees it on the ticket instead of having to go and look in the tracker.',
        'done'     => 'At least one tracker connection accepts updates.',
        'link'     => 'system/integrations/',
        'check'    => ['rows', 'integration_connections', 'inbound_enabled = 1 AND is_active = 1'],
    ],
    [
        'id'       => 'system.tracker_send_attachments',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'integrations',
        'title'    => 'Attachments sent to the tracker',
        'what'     => 'Files deliberately attached to a ticket go with it when it is escalated. Images embedded in emails - signatures, logos - are never sent.',
        'why'      => 'On a bug report the screenshot usually is the report. Sending it saves the developer asking for it and the requester sending it twice.',
        'done'     => 'At least one active tracker connection sends attachments.',
        'link'     => 'system/integrations/',
        'check'    => ['rows', 'integration_connections', 'send_attachments = 1 AND is_active = 1'],
    ],
    [
        'id'       => 'system.tracker_project_mapping',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'integrations',
        'title'    => 'Tracker project routing',
        'what'     => 'A default project for issues raised from tickets, with exceptions by company or department.',
        'why'      => 'Nobody has to know or type a project key when escalating, and issues for each client or team land in the right place automatically.',
        'done'     => 'At least one project mapping is saved on a tracker connection.',
        'link'     => 'system/integrations/',
        'check'    => ['rows', 'integration_field_maps', "map_type = 'project'"],
    ],
    [
        'id'       => 'system.tracker_issue_type_mapping',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'integrations',
        'title'    => 'Ticket type to issue type',
        'what'     => 'Which issue type in the tracker each ticket type becomes - a fault becomes a Bug, a request a Story, and so on.',
        'why'      => 'Escalated work arrives already classified the way the development team sorts its backlog.',
        'done'     => 'At least one ticket type is mapped to an issue type.',
        'link'     => 'system/integrations/',
        'check'    => ['rows', 'integration_field_maps', "map_type = 'issue_type'"],
    ],
    [
        'id'       => 'system.tracker_priority_mapping',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'integrations',
        'title'    => 'Priority mapping to the tracker',
        'what'     => 'Which tracker priority each ticket priority becomes when an issue is raised. There is deliberately no default.',
        'why'      => 'A P1 ticket reaches the developers as their highest priority rather than as plain text in a description they may not read.',
        'done'     => 'At least one ticket priority is mapped to a tracker priority.',
        'link'     => 'system/integrations/',
        'check'    => ['rows', 'integration_field_maps', "map_type = 'priority'"],
    ],
    [
        'id'       => 'system.tracker_company_pinned',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'security',
        'title'    => 'Tracker limited to one company',
        'what'     => 'A tracker connection restricted to one company, so only that company\'s tickets can be escalated to it.',
        'why'      => 'When a client has its own Jira or Azure DevOps, nobody can accidentally raise another client\'s ticket in it.',
        'done'     => 'At least one tracker connection is limited to a company.',
        'link'     => 'system/integrations/',
        'check'    => ['rows', 'integration_connections', 'tenant_id IS NOT NULL'],
    ],
    [
        'id'       => 'system.tracker_poll',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'automation',
        'title'    => 'Tracker status polling',
        'what'     => 'The scheduled job (cron/integration_poll.php) that checks each linked issue for status changes and new comments.',
        'why'      => 'Without it a linked issue\'s status never updates on the ticket, and the tracker workflow triggers never fire.',
        'done'     => 'The tracker poll has run in the last 7 days.',
        'link'     => 'system/integrations/',
        'check'    => ['sql', "SELECT COUNT(*) FROM system_settings WHERE setting_key = 'integration_cron_last_run' AND setting_value >= UTC_TIMESTAMP() - INTERVAL 7 DAY"],
    ],

    // ── Integrations: Slack  ────────────────────────────
];
